// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countInvitations = `-- name: CountInvitations :one
SELECT count(*) FROM invitations
`

func (q *Queries) CountInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    source, session_id, event_date, event_time,
    food_id, food_label, food_emoji,
    place_id, place_label, place_emoji,
    invite_text, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, source, session_id, event_date, event_time, food_id, food_label, food_emoji, place_id, place_label, place_emoji, invite_text, user_agent, created_at
`

type CreateInvitationParams struct {
	Source     string    `json:"source"`
	SessionID  string    `json:"session_id"`
	EventDate  time.Time `json:"event_date"`
	EventTime  string    `json:"event_time"`
	FoodID     string    `json:"food_id"`
	FoodLabel  string    `json:"food_label"`
	FoodEmoji  string    `json:"food_emoji"`
	PlaceID    string    `json:"place_id"`
	PlaceLabel string    `json:"place_label"`
	PlaceEmoji string    `json:"place_emoji"`
	InviteText string    `json:"invite_text"`
	UserAgent  string    `json:"user_agent"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Source,
		arg.SessionID,
		arg.EventDate,
		arg.EventTime,
		arg.FoodID,
		arg.FoodLabel,
		arg.FoodEmoji,
		arg.PlaceID,
		arg.PlaceLabel,
		arg.PlaceEmoji,
		arg.InviteText,
		arg.UserAgent,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SessionID,
		&i.EventDate,
		&i.EventTime,
		&i.FoodID,
		&i.FoodLabel,
		&i.FoodEmoji,
		&i.PlaceID,
		&i.PlaceLabel,
		&i.PlaceEmoji,
		&i.InviteText,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, source, session_id, event_date, event_time, food_id, food_label, food_emoji, place_id, place_label, place_emoji, invite_text, user_agent, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SessionID,
		&i.EventDate,
		&i.EventTime,
		&i.FoodID,
		&i.FoodLabel,
		&i.FoodEmoji,
		&i.PlaceID,
		&i.PlaceLabel,
		&i.PlaceEmoji,
		&i.InviteText,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, source, session_id, event_date, event_time, food_id, food_label, food_emoji, place_id, place_label, place_emoji, invite_text, user_agent, created_at FROM invitations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListInvitationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SessionID,
			&i.EventDate,
			&i.EventTime,
			&i.FoodID,
			&i.FoodLabel,
			&i.FoodEmoji,
			&i.PlaceID,
			&i.PlaceLabel,
			&i.PlaceEmoji,
			&i.InviteText,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
