// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Invitation struct {
	ID         uuid.UUID `json:"id"`
	Source     string    `json:"source"`
	SessionID  string    `json:"session_id"`
	EventDate  time.Time `json:"event_date"`
	EventTime  string    `json:"event_time"`
	FoodID     string    `json:"food_id"`
	FoodLabel  string    `json:"food_label"`
	FoodEmoji  string    `json:"food_emoji"`
	PlaceID    string    `json:"place_id"`
	PlaceLabel string    `json:"place_label"`
	PlaceEmoji string    `json:"place_emoji"`
	InviteText string    `json:"invite_text"`
	UserAgent  string    `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
}

type Post struct {
	ID          uuid.UUID  `json:"id"`
	Locale      string     `json:"locale"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Body        string     `json:"body"`
	Tags        []string   `json:"tags"`
	Cover       string     `json:"cover"`
	Featured    bool       `json:"featured"`
	Draft       bool       `json:"draft"`
	ContentDate time.Time  `json:"content_date"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID `json:"id"`
	Locale      string    `json:"locale"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	Tags        []string  `json:"tags"`
	Stack       []string  `json:"stack"`
	Url         string    `json:"url"`
	Repo        string    `json:"repo"`
	SortOrder   int32     `json:"sort_order"`
	Featured    bool      `json:"featured"`
	Draft       bool      `json:"draft"`
	ContentDate time.Time `json:"content_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
