// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    locale, slug, title, description, body, tags, cover,
    featured, draft, content_date, published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Locale      string     `json:"locale"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Body        string     `json:"body"`
	Tags        []string   `json:"tags"`
	Cover       string     `json:"cover"`
	Featured    bool       `json:"featured"`
	Draft       bool       `json:"draft"`
	ContentDate time.Time  `json:"content_date"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Cover,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at FROM posts
WHERE ($1::text IS NULL OR locale = $1)
  AND ($2::boolean IS NULL OR draft = $2)
ORDER BY content_date DESC, created_at DESC
`

type ListPostsParams struct {
	Locale *string `json:"locale"`
	Draft  *bool   `json:"draft"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Locale, arg.Draft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Locale,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.Tags,
			&i.Cover,
			&i.Featured,
			&i.Draft,
			&i.ContentDate,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPostPublished = `-- name: SetPostPublished :one
UPDATE posts
SET draft = $2,
    published_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at
`

type SetPostPublishedParams struct {
	ID          uuid.UUID  `json:"id"`
	Draft       bool       `json:"draft"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) SetPostPublished(ctx context.Context, arg SetPostPublishedParams) (Post, error) {
	row := q.db.QueryRow(ctx, setPostPublished, arg.ID, arg.Draft, arg.PublishedAt)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET locale = $2,
    slug = $3,
    title = $4,
    description = $5,
    body = $6,
    tags = $7,
    cover = $8,
    featured = $9,
    draft = $10,
    content_date = $11,
    published_at = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID          uuid.UUID  `json:"id"`
	Locale      string     `json:"locale"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Body        string     `json:"body"`
	Tags        []string   `json:"tags"`
	Cover       string     `json:"cover"`
	Featured    bool       `json:"featured"`
	Draft       bool       `json:"draft"`
	ContentDate time.Time  `json:"content_date"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Cover,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at FROM posts
WHERE draft = false AND locale = $1 AND slug = $2
`

type GetPublishedPostBySlugParams struct {
	Locale string `json:"locale"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, arg GetPublishedPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, arg.Locale, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at FROM posts
WHERE draft = false
  AND ($1::text IS NULL OR locale = $1)
ORDER BY content_date DESC, created_at DESC
`

func (q *Queries) ListPublishedPosts(ctx context.Context, locale *string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Locale,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.Tags,
			&i.Cover,
			&i.Featured,
			&i.Draft,
			&i.ContentDate,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (
    locale, slug, title, description, body, tags, cover,
    featured, draft, content_date, published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (locale, slug) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    body = EXCLUDED.body,
    tags = EXCLUDED.tags,
    cover = EXCLUDED.cover,
    featured = EXCLUDED.featured,
    draft = EXCLUDED.draft,
    content_date = EXCLUDED.content_date,
    published_at = EXCLUDED.published_at,
    updated_at = now()
RETURNING id, locale, slug, title, description, body, tags, cover, featured, draft, content_date, published_at, created_at, updated_at
`

type UpsertPostParams struct {
	Locale      string     `json:"locale"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Body        string     `json:"body"`
	Tags        []string   `json:"tags"`
	Cover       string     `json:"cover"`
	Featured    bool       `json:"featured"`
	Draft       bool       `json:"draft"`
	ContentDate time.Time  `json:"content_date"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, upsertPost,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Cover,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Cover,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
