// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    locale, slug, title, description, body, tags, stack, url, repo,
    sort_order, featured, draft, content_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at
`

type CreateProjectParams struct {
	Locale      string    `json:"locale"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	Tags        []string  `json:"tags"`
	Stack       []string  `json:"stack"`
	Url         string    `json:"url"`
	Repo        string    `json:"repo"`
	SortOrder   int32     `json:"sort_order"`
	Featured    bool      `json:"featured"`
	Draft       bool      `json:"draft"`
	ContentDate time.Time `json:"content_date"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Stack,
		arg.Url,
		arg.Repo,
		arg.SortOrder,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Stack,
		&i.Url,
		&i.Repo,
		&i.SortOrder,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Stack,
		&i.Url,
		&i.Repo,
		&i.SortOrder,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at FROM projects
WHERE ($1::text IS NULL OR locale = $1)
  AND ($2::boolean IS NULL OR draft = $2)
ORDER BY sort_order DESC, content_date DESC
`

type ListProjectsParams struct {
	Locale *string `json:"locale"`
	Draft  *bool   `json:"draft"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Locale, arg.Draft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Locale,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.Tags,
			&i.Stack,
			&i.Url,
			&i.Repo,
			&i.SortOrder,
			&i.Featured,
			&i.Draft,
			&i.ContentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET locale = $2,
    slug = $3,
    title = $4,
    description = $5,
    body = $6,
    tags = $7,
    stack = $8,
    url = $9,
    repo = $10,
    sort_order = $11,
    featured = $12,
    draft = $13,
    content_date = $14,
    updated_at = now()
WHERE id = $1
RETURNING id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Locale      string    `json:"locale"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	Tags        []string  `json:"tags"`
	Stack       []string  `json:"stack"`
	Url         string    `json:"url"`
	Repo        string    `json:"repo"`
	SortOrder   int32     `json:"sort_order"`
	Featured    bool      `json:"featured"`
	Draft       bool      `json:"draft"`
	ContentDate time.Time `json:"content_date"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Stack,
		arg.Url,
		arg.Repo,
		arg.SortOrder,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Stack,
		&i.Url,
		&i.Repo,
		&i.SortOrder,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProjectBySlug = `-- name: GetPublishedProjectBySlug :one
SELECT id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at FROM projects
WHERE draft = false AND locale = $1 AND slug = $2
`

type GetPublishedProjectBySlugParams struct {
	Locale string `json:"locale"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetPublishedProjectBySlug(ctx context.Context, arg GetPublishedProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getPublishedProjectBySlug, arg.Locale, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Stack,
		&i.Url,
		&i.Repo,
		&i.SortOrder,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedProjects = `-- name: ListPublishedProjects :many
SELECT id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at FROM projects
WHERE draft = false
  AND ($1::text IS NULL OR locale = $1)
ORDER BY sort_order DESC, content_date DESC
`

func (q *Queries) ListPublishedProjects(ctx context.Context, locale *string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listPublishedProjects, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Locale,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.Tags,
			&i.Stack,
			&i.Url,
			&i.Repo,
			&i.SortOrder,
			&i.Featured,
			&i.Draft,
			&i.ContentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (
    locale, slug, title, description, body, tags, stack, url, repo,
    sort_order, featured, draft, content_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (locale, slug) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    body = EXCLUDED.body,
    tags = EXCLUDED.tags,
    stack = EXCLUDED.stack,
    url = EXCLUDED.url,
    repo = EXCLUDED.repo,
    sort_order = EXCLUDED.sort_order,
    featured = EXCLUDED.featured,
    draft = EXCLUDED.draft,
    content_date = EXCLUDED.content_date,
    updated_at = now()
RETURNING id, locale, slug, title, description, body, tags, stack, url, repo, sort_order, featured, draft, content_date, created_at, updated_at
`

type UpsertProjectParams struct {
	Locale      string    `json:"locale"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	Tags        []string  `json:"tags"`
	Stack       []string  `json:"stack"`
	Url         string    `json:"url"`
	Repo        string    `json:"repo"`
	SortOrder   int32     `json:"sort_order"`
	Featured    bool      `json:"featured"`
	Draft       bool      `json:"draft"`
	ContentDate time.Time `json:"content_date"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Locale,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Tags,
		arg.Stack,
		arg.Url,
		arg.Repo,
		arg.SortOrder,
		arg.Featured,
		arg.Draft,
		arg.ContentDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Locale,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Tags,
		&i.Stack,
		&i.Url,
		&i.Repo,
		&i.SortOrder,
		&i.Featured,
		&i.Draft,
		&i.ContentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
