// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	GetPostByID(ctx context.Context, id uuid.UUID) (Post, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetPublishedPostBySlug(ctx context.Context, arg GetPublishedPostBySlugParams) (Post, error)
	GetPublishedProjectBySlug(ctx context.Context, arg GetPublishedProjectBySlugParams) (Project, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListPublishedPosts(ctx context.Context, locale *string) ([]Post, error)
	ListPublishedProjects(ctx context.Context, locale *string) ([]Project, error)
	SetPostPublished(ctx context.Context, arg SetPostPublishedParams) (Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
